# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unary.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bunary.proto\x12\x05unary\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x16\n\x05Words\x12\r\n\x05words\x18\x01 \x03(\t\"3\n\x07ScanReq\x12\x0c\n\x04\x62ook\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\t\x12\x0b\n\x03\x65nd\x18\x03 \x01(\t\"\"\n\x0b\x46requencies\x12\x13\n\x0b\x66requencies\x18\x01 \x03(\x02\")\n\x07ScanRes\x12\x1e\n\x05pairs\x18\x01 \x03(\x0b\x32\x0f.unary.Wordpair\")\n\x08Wordpair\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0f\n\x07meaning\x18\x02 \x01(\t\"4\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\x32\xaa\x01\n\x05Unary\x12=\n\x11GetServerResponse\x12\x0e.unary.Message\x1a\x16.unary.MessageResponse\"\x00\x12\x38\n\x12GetWordFrequencies\x12\x0c.unary.Words\x1a\x12.unary.Frequencies\"\x00\x12(\n\x04Scan\x12\x0e.unary.ScanReq\x1a\x0e.unary.ScanRes\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unary_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=22
  _globals['_MESSAGE']._serialized_end=48
  _globals['_WORDS']._serialized_start=50
  _globals['_WORDS']._serialized_end=72
  _globals['_SCANREQ']._serialized_start=74
  _globals['_SCANREQ']._serialized_end=125
  _globals['_FREQUENCIES']._serialized_start=127
  _globals['_FREQUENCIES']._serialized_end=161
  _globals['_SCANRES']._serialized_start=163
  _globals['_SCANRES']._serialized_end=204
  _globals['_WORDPAIR']._serialized_start=206
  _globals['_WORDPAIR']._serialized_end=247
  _globals['_MESSAGERESPONSE']._serialized_start=249
  _globals['_MESSAGERESPONSE']._serialized_end=301
  _globals['_UNARY']._serialized_start=304
  _globals['_UNARY']._serialized_end=474
# @@protoc_insertion_point(module_scope)
